### ISSUE TITLE
TypeError with standard configuration

### ISSUE THREAD

**Issue by theinnocentprogrammer** [paolotremadio/homebridge-automation-chromecast-play#11]
Hi all,

Facing the following issue when compiling with the basic config.json suggestion and media json file:

`[06/09/2023, 14:01:18] TypeError: characteristic.internalHAPRepresentation is not a function
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:962:82
    at Array.map (<anonymous>)
    at Switch.Service.internalHAPRepresentation (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:962:45)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1171:54
    at Array.map (<anonymous>)
    at Accessory.internalHAPRepresentation (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1171:31)
    at Bridge.Accessory.internalHAPRepresentation (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1178:36)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1291:25)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)`

How to fix this?

**Comment by paolotremadio** [comment]
Sorry but this plugin is no longer supported. Feel free to have a look at the code and try to fix it. The error message is very generic and there's no reference to this plugin, it would be very difficult for me to provide support.
